CREATE TABLE users (
  id BIGSERIAL PRIMARY KEY,
  login TEXT NOT NULL UNIQUE,
  password TEXT NOT NULL,
  roles TEXT[] NOT NULL DEFAULT '{ROLE_USER}',
  avatar TEXT NOT NULL DEFAULT 'noavatar.svg',
  removed BOOLEAN NOT NULL DEFAULT FALSE,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE tokens (
    userId BIGINT NOT NULL REFERENCES users,
    token TEXT PRIMARY KEY
);